### ISSUE TITLE
ELA2.0_NAV project's Gui code

### ISSUE THREAD

**Issue by gaohaozhang** [LimJingXiang1226/ELA2.0_NAV#2]
Hello, thank you very much for your contribution to your work. It is a very meaningful work. Please tell me that I did not find the relevant Gui code shown in the ELA2.0_NAV project demonstration video in the code. Can you share this part of the code?

**Comment by LimJingXiang1226** [comment]
The code is in "ella2_gui" folder under "src" folder

**Comment by gaohaozhang** [comment]
Thank you very much for your reply

**Comment by gaohaozhang** [comment]
I have studied your work for two days, but I still haven't successfully run it. I'm very sorry to bother you again. I encountered two problems. The first one is why I need to reference two ORBSLAM3 ，_https://github.com/zang09 /ORB-SLAM3-STEREO-FIXED_
and _https://github.com/zang09/ORB_SLAM3_ROS2_. Do these two cause conflicts and cause me to fail to run successfully? If I need to download this project, which one should I download and which folder should I put it in?Secondly, https://github.com/LimJingXiang1226/ELA2.0_NAV?tab=readme-ov-file#instruction-to-install-orb-slam3?why does the ELA2.0 BRINGUP part always appear， ros2 launch ella2_bringup ella2_bringup.launch.xml
Package 'ella2_bringup' not found: "package 'ella2_bringup' not found, searching: ['/opt/ros/foxy']"

**Comment by LimJingXiang1226** [comment]
The first link have clearer instruction for downloading ORB-SLAM3, I use the second link to download the package due to the fixed stereo mode.

as for the package not found pls check if you have "colcon build" the workspace/package, or did you forget to source your bashrc/workspace file

**Comment by gaohaozhang** [comment]
Thank you very much, dear friend

**Comment by gaohaozhang** [comment]
After many days of hard work, I finally successfully ran your project, and I deeply appreciate the contribution of your work. Please tell me how to use my binocular camera to perform SLAM and NAV

**Comment by gaohaozhang** [comment]
After many days of hard work, I finally successfully ran your project (because I am not a professional and encountered a lot of build problems and didn’t know how to solve them), and I deeply appreciate the contribution of your work. I'm very sorry to bother you again. Please tell me how to use my binocular camera to perform SLAM and NAV.
